* basic cross browser additions for edge, firefox, and possibly more
time-less-ness/trust-assembly pull request #8
Opened 2024-11-06 21:48 UTC by gholtorf

* makes use of the extension.js library to let you build in most windows browsers.  Which browsers it builds for depends on what you have installed on your machine. (does not cover safari)
* you will need to run two commands (in readme) the first time you build, then never again.
* extension required the src/popup.js file even if it is empty.
* firefox also needs you to add self signed certificates. Uses the mkcert library.

2024-11-07 21:13 UTC, adhurjaty commented
I added source map building in [this PR](https://github.com/time-less-ness/trust-assembly/pull/9). Does this PR remove the need for mine?

2024-11-11 14:49 UTC, gholtorf commented
> I added source map building in [this PR](https://github.com/time-less-ness/trust-assembly/pull/9). Does this PR remove the need for mine?

No, they should be able to merge.  Mine does not have a source map.

2024-11-13 03:53 UTC, Melvillian requested changes
Nice job on improving the dev experience and abstracting away annoying cross-platform annoyances!

I tested everything with chrome and it worked well. See the requests I made, which are mostly informative/cosmetic.

one thing I couldn't get working according to the instructions here was Firefox. I ran into one issue with the "Temporary Add-on" Firefox setup process, and fixed it by following the advice [here](https://stackoverflow.com/a/75203925), basically I did a hacky thing where I removed the `service_worker` key, which obviously would break Chrome. But even with that, I couldn't get the extension working in Firefox. Were you able to get it working in firefox following those instructions? I'm on a Mac Apple Silicon.

2024-11-13 03:53 UTC, Melvillian commented on ui/browser-extension/README.md
> +npm run build
I think you meant `npm run start` here.

2024-11-13 03:53 UTC, Melvillian commented on ui/browser-extension/README.md
> +# you only need to run these commands once before building
we can remove this comment. I was able to pull your PR, install the extension with `npm install` (which people won't need to do specifically for the `extension` dependency since they'll get it when they run `npm install` upon first cloning the repo), and then I was able to run `npm run dev` just fine.

2024-11-13 03:53 UTC, Melvillian commented on ui/browser-extension/README.md
> +#build trust assembly with extension.js
lines 20-22 can be deleted, see my comment above.

2024-11-13 03:53 UTC, Melvillian commented on ui/browser-extension/manifest.json
> +    "scripts": ["src/background.ts"]
I get this error in chrome when I try to load the extension:

<img width="680" alt="image" src="https://github.com/user-attachments/assets/630ab815-5dd3-481e-b33f-42bb05b3c267">

why did we need to add this in originally? I removed it and ran `npm run dev` and everything worked fine, so unless there's a reason I'm not seeing, I think we should remove it.

2024-11-13 03:53 UTC, Melvillian commented on ui/browser-extension/README.md
> +#set up certs firefox if you have it
Can you move this to the `#### Load the Extension into Firefox` section? Some of us don't use firefox, and we should make people who don't have firefox do this scary command unnecessarily.

2024-11-13 03:53 UTC, Melvillian commented on ui/browser-extension/README.md
> +B.
I say we remove all the old manual way of doing it (i.e. all the stuff under B) because right now it's not clear what if `npm run dev` is sufficient, or they need to do `npm run dev` as well as all the manual stuff. extension.js let's us simplify all this :D

2024-11-13 03:53 UTC, Melvillian commented on ui/browser-extension/package.json
> +  "background": {
`background` is not a standard package.json key, and I'm not sure what it's doing here. please remove

2024-11-13 03:53 UTC, Melvillian commented on ui/browser-extension/package.json
> +    "start": "webpack & extension start --browser=chrome,edge",
I know it says to do this in extension.js's github README, but I can't tell what this does and it's not actually listed as a command [in the docs](https://extension.js.org/docs/commands/dev). Let's remove it so the package.json scripts are clearer on what commands matter.

2024-11-13 03:54 UTC, Melvillian commented
Oh also, please pull in the latest source-map changes on `main` from me merging #9

2024-11-13 21:41 UTC, Melvillian commented on ui/browser-extension/README.md
> +#build trust assembly with extension.js
I think I see what you're saying; that we should tell them to run `npm install`. Yes, that makes sense to me, let's do that.

However, i don't think we need to tell them `cd ../trust-assembly/ui/browser-extension`, because that assumes they're in some sibling directory of `trust-assembly` (that's what `../trust-assembly/...` is doing) when I think it's safe to assume the user knows they need to be in the `browser-extension` directory, given they're reading the `browser-extension/README.md` file. That is a given in virtually all node.js projects I've seen.

We also want to remove `npm install extension --save-dev`, because `extension` will be installed when they run `npm install`.

2024-11-13 21:41 UTC, Melvillian commented on ui/browser-extension/README.md
> +npm run build
though, see what I said about the `start` npm script; I think we should remove it.

2024-12-01 16:38 UTC, closed without merging